/******************************
中车专属破解
畅K互娱
小程序
*******************************
[rewrite_local]
# > 畅K互娱VIP全部功能

^http[s]?:\/\/.+ycvod.+(My|Home).+(myVipNew|UserInfo) url script-response-body https://raw.githubusercontent.com/Q39547190/niubi/main/changKHY.js

[mitm] 
hostname =*interface.ycvod.cn*

******************************/

var body = $response.body;
var url = $request.url;
var vip = JSON.parse(body);

if (url.indexOf("/Home/UserInfo") != -1) {
    vip.data.VIP_STATUS = 2;
    vip.data.EXPIRE_DATE = 32493834549;
    vip.data.FREE_PLAY_STATUS = 1;
body = JSON.stringify(vip);
}

if (url.indexOf("/My/myVipNew") != -1) {
    vip.data.menu = [{
      "ID": 2309,
      "TYPE": "",
      "MENU_TYPE": 5,
      "MENU_NAME": "中车专属破解",
      "MENU_SORT": 1000,
      "IS_ENABLE": "1",
      "MENU_COMMENTS": "手机顶歌更方便",
      "MENU_ICON_URL": "http:\/\/wximg.ycvod.cn\/jisudiange22.png",
      "REDIRECT_TYPE": 2,
      "REDIRECT_URL": null,
      "REDIRECT_PARAMS": "http:\/\/wximg.ycvod.cn\/jisudiange1%20%281%29.png",
      "CREATED_BY": null,
      "CREATED_TIME": null,
      "UPDATED_BY": "Administrator",
      "UPDATED_TIME": "2021-05-08 16:38:29",
      "SHOW_NAME": "手机上无法置顶歌曲&手机上可以置顶歌曲",
      "PAGE_URL": null,
      "SAMPLE_TYPE": null,
      "SAMPLE_URL": null,
      "FREE_TRIAL_TYPE": null,
      "COVER_IMG": null,
      "VERSION": "",
      "PAY_TYPE": "hy_lx",
      "NORMAL_INTRO": "手机上无法置顶歌曲",
      "VIP_INTRO": "手机上可以置顶歌曲"
    }, {
      "ID": 2304,
      "TYPE": "",
      "MENU_TYPE": 5,
      "MENU_NAME": "中车专属破解",
      "MENU_SORT": 990,
      "IS_ENABLE": "1",
      "MENU_COMMENTS": "点歌置顶不被插",
      "MENU_ICON_URL": "http:\/\/pwgrcsdx9.bkt.clouddn.com\/%E6%9D%83%E7%9B%8A%E8%8F%9C%E5%8D%95-%E7%BD%AE%E9%A1%B6%E6%AD%8C%E6%9B%B2.png",
      "REDIRECT_TYPE": 2,
      "REDIRECT_URL": null,
      "REDIRECT_PARAMS": "http:\/\/pwgrcsdx9.bkt.clouddn.com\/%E6%9D%83%E7%9B%8A%E5%B9%BF%E5%91%8A-%E7%BD%AE%E9%A1%B6.png",
      "CREATED_BY": "chenyong",
      "CREATED_TIME": "2019-08-19 22:10:57",
      "UPDATED_BY": "肖剑",
      "UPDATED_TIME": "2022-06-28 16:38:48",
      "SHOW_NAME": "置顶歌曲后，可以被插歌&置顶歌曲后，享优先置顶特权，不允许被插歌",
      "PAGE_URL": null,
      "SAMPLE_TYPE": null,
      "SAMPLE_URL": null,
      "FREE_TRIAL_TYPE": null,
      "COVER_IMG": null,
      "VERSION": "",
      "PAY_TYPE": "hy_lx",
      "NORMAL_INTRO": "置顶歌曲后，可以被插歌",
      "VIP_INTRO": "置顶歌曲后，享优先置顶特权，不允许被插歌"
    }, {
      "ID": 2307,
      "TYPE": "",
      "MENU_TYPE": 5,
      "MENU_NAME": "中车专属破解",
      "MENU_SORT": 980,
      "IS_ENABLE": "1",
      "MENU_COMMENTS": "纯净无广告",
      "MENU_ICON_URL": "http:\/\/wximg.ycvod.cn\/pbggicon.png",
      "REDIRECT_TYPE": 2,
      "REDIRECT_URL": null,
      "REDIRECT_PARAMS": "http:\/\/wximg.ycvod.cn\/pbggxq.png",
      "CREATED_BY": null,
      "CREATED_TIME": null,
      "UPDATED_BY": "侯欣卫",
      "UPDATED_TIME": "2022-08-05 16:51:53",
      "SHOW_NAME": "使用过程中有微信广告出现&屏蔽所有微信广告，操作体验更加棒",
      "PAGE_URL": null,
      "SAMPLE_TYPE": null,
      "SAMPLE_URL": null,
      "FREE_TRIAL_TYPE": null,
      "COVER_IMG": null,
      "VERSION": "",
      "PAY_TYPE": "hy_lx",
      "NORMAL_INTRO": "使用过程中有微信广告出现",
      "VIP_INTRO": "屏蔽所有微信广告，操作体验更加棒"
    }, {
      "ID": 2305,
      "TYPE": "",
      "MENU_TYPE": 5,
      "MENU_NAME": "中车专属破解",
      "MENU_SORT": 970,
      "IS_ENABLE": "1",
      "MENU_COMMENTS": "不限时、不限量",
      "MENU_ICON_URL": "http:\/\/pwgrcsdx9.bkt.clouddn.com\/%E6%9D%83%E7%9B%8A%E8%8F%9C%E5%8D%95-%E5%B8%B8%E5%94%B1%E6%AD%8C%E6%9B%B2.png",
      "REDIRECT_TYPE": 2,
      "REDIRECT_URL": "",
      "REDIRECT_PARAMS": "http:\/\/pwgrcsdx9.bkt.clouddn.com\/%E6%9D%83%E7%9B%8A%E5%B9%BF%E5%91%8A-%E5%B8%B8%E5%94%B1%E6%AD%8C%E6%9B%B2%E4%BF%9D%E5%AD%98.png",
      "CREATED_BY": "chenyong",
      "CREATED_TIME": "2019-08-19 22:10:57",
      "UPDATED_BY": "chenyong",
      "UPDATED_TIME": "2019-08-19 22:10:57",
      "SHOW_NAME": "收藏数量和时间有所限制&歌曲任意收藏，不限数量，不限时长，永久保存",
      "PAGE_URL": null,
      "SAMPLE_TYPE": null,
      "SAMPLE_URL": null,
      "FREE_TRIAL_TYPE": null,
      "COVER_IMG": "",
      "VERSION": "",
      "PAY_TYPE": "hy_lx",
      "NORMAL_INTRO": "收藏数量和时间有所限制",
      "VIP_INTRO": "歌曲任意收藏，不限数量，不限时长，永久保存"
    }, {
      "ID": 2306,
      "TYPE": "",
      "MENU_TYPE": 5,
      "MENU_NAME": "中车专属破解",
      "MENU_SORT": 960,
      "IS_ENABLE": "1",
      "MENU_COMMENTS": "搜歌切歌更方便",
      "MENU_ICON_URL": "http:\/\/wximg.ycvod.cn\/yuyinicon.png",
      "REDIRECT_TYPE": 2,
      "REDIRECT_URL": null,
      "REDIRECT_PARAMS": "http:\/\/wximg.ycvod.cn\/YUYINDIANGEXINGQ.png",
      "CREATED_BY": null,
      "CREATED_TIME": null,
      "UPDATED_BY": "何潜墨",
      "UPDATED_TIME": "2022-05-19 10:44:08",
      "SHOW_NAME": "无法使用&可以使用，通过语音在手机上快捷的完成搜歌、切歌、调音量等操作",
      "PAGE_URL": null,
      "SAMPLE_TYPE": null,
      "SAMPLE_URL": null,
      "FREE_TRIAL_TYPE": null,
      "COVER_IMG": null,
      "VERSION": "",
      "PAY_TYPE": "hy_lx",
      "NORMAL_INTRO": "无法使用",
      "VIP_INTRO": "可以使用，通过语音在手机上快捷的完成搜歌、切歌、调音量等操作"
    }, {
      "ID": 2311,
      "TYPE": "",
      "MENU_TYPE": 5,
      "MENU_NAME": "中车专属破解",
      "MENU_SORT": 950,
      "IS_ENABLE": "1",
      "MENU_COMMENTS": "免费发霸屏礼物",
      "MENU_ICON_URL": "http:\/\/pwgrcsdx9.bkt.clouddn.com\/%E6%9D%83%E7%9B%8A%E8%8F%9C%E5%8D%95-%E9%80%81%E7%A5%9D%E7%A6%8F.png",
      "REDIRECT_TYPE": 2,
      "REDIRECT_URL": null,
      "REDIRECT_PARAMS": "http:\/\/pwgrcsdx9.bkt.clouddn.com\/%E6%9D%83%E7%9B%8A%E5%B9%BF%E5%91%8A-%E9%80%81%E7%A5%9D%E7%A6%8F.png",
      "CREATED_BY": null,
      "CREATED_TIME": null,
      "UPDATED_BY": null,
      "UPDATED_TIME": null,
      "SHOW_NAME": "单次付费使用&免费使用，不限量",
      "PAGE_URL": null,
      "SAMPLE_TYPE": null,
      "SAMPLE_URL": null,
      "FREE_TRIAL_TYPE": 0,
      "COVER_IMG": "",
      "VERSION": "",
      "PAY_TYPE": "hy_lx",
      "NORMAL_INTRO": "单次付费使用",
      "VIP_INTRO": "免费使用，不限量"
    }, {
      "ID": 2312,
      "TYPE": "",
      "MENU_TYPE": 5,
      "MENU_NAME": "中车专属破解",
      "MENU_SORT": 940,
      "IS_ENABLE": "1",
      "MENU_COMMENTS": "免费发照片",
      "MENU_ICON_URL": "http:\/\/pwgrcsdx9.bkt.clouddn.com\/uploadphoto-icon-vip.png.png",
      "REDIRECT_TYPE": 2,
      "REDIRECT_URL": null,
      "REDIRECT_PARAMS": "http:\/\/pwgrcsdx9.bkt.clouddn.com\/uploadphoto-vip-detail-new.png.png",
      "CREATED_BY": null,
      "CREATED_TIME": null,
      "UPDATED_BY": null,
      "UPDATED_TIME": null,
      "SHOW_NAME": "单次付费使用&免费使用，不限量",
      "PAGE_URL": null,
      "SAMPLE_TYPE": null,
      "SAMPLE_URL": null,
      "FREE_TRIAL_TYPE": 0,
      "COVER_IMG": "",
      "VERSION": "",
      "PAY_TYPE": "hy_lx",
      "NORMAL_INTRO": "单次付费使用",
      "VIP_INTRO": "免费使用，不限量"
    }, {
      "ID": 2313,
      "TYPE": "",
      "MENU_TYPE": 5,
      "MENU_NAME": "中车专属破解",
      "MENU_SORT": 930,
      "IS_ENABLE": "1",
      "MENU_COMMENTS": "免费发表情",
      "MENU_ICON_URL": "http:\/\/pwgrcsdx9.bkt.clouddn.com\/%E6%9D%83%E7%9B%8A%E8%8F%9C%E5%8D%95-%E5%8F%91%E8%A1%A8%E6%83%85.png",
      "REDIRECT_TYPE": 2,
      "REDIRECT_URL": null,
      "REDIRECT_PARAMS": "http:\/\/pwgrcsdx9.bkt.clouddn.com\/%E6%9D%83%E7%9B%8A%E5%B9%BF%E5%91%8A-%E5%8F%91%E8%A1%A8%E6%83%85.png",
      "CREATED_BY": null,
      "CREATED_TIME": null,
      "UPDATED_BY": null,
      "UPDATED_TIME": null,
      "SHOW_NAME": "单次付费使用&免费使用，不限量",
      "PAGE_URL": null,
      "SAMPLE_TYPE": null,
      "SAMPLE_URL": null,
      "FREE_TRIAL_TYPE": 0,
      "COVER_IMG": "",
      "VERSION": "",
      "PAY_TYPE": "hy_lx",
      "NORMAL_INTRO": "单次付费使用",
      "VIP_INTRO": "免费使用，不限量"
    }, {
      "ID": 2314,
      "TYPE": "",
      "MENU_TYPE": 5,
      "MENU_NAME": "中车专属破解",
      "MENU_SORT": 920,
      "IS_ENABLE": "1",
      "MENU_COMMENTS": "免费发弹幕",
      "MENU_ICON_URL": "http:\/\/pwgrcsdx9.bkt.clouddn.com\/%E6%9D%83%E7%9B%8A%E8%8F%9C%E5%8D%95-%E5%8F%91%E5%BC%B9%E5%B9%95.png",
      "REDIRECT_TYPE": 2,
      "REDIRECT_URL": null,
      "REDIRECT_PARAMS": "http:\/\/pwgrcsdx9.bkt.clouddn.com\/%E6%9D%83%E7%9B%8A%E5%B9%BF%E5%91%8A-%E5%8F%91%E5%BC%B9%E5%B9%95.png",
      "CREATED_BY": null,
      "CREATED_TIME": null,
      "UPDATED_BY": null,
      "UPDATED_TIME": null,
      "SHOW_NAME": "单次付费使用&免费使用，不限量",
      "PAGE_URL": null,
      "SAMPLE_TYPE": null,
      "SAMPLE_URL": null,
      "FREE_TRIAL_TYPE": 0,
      "COVER_IMG": "",
      "VERSION": "",
      "PAY_TYPE": "hy_lx",
      "NORMAL_INTRO": "单次付费使用",
      "VIP_INTRO": "免费使用，不限量"
    }, {
      "ID": 2308,
      "TYPE": "",
      "MENU_TYPE": 5,
      "MENU_NAME": "中车专属破解",
      "MENU_SORT": 910,
      "IS_ENABLE": "1",
      "MENU_COMMENTS": "专属登场特效",
      "MENU_ICON_URL": "http:\/\/wximg.ycvod.cn\/VIPbiaozhi11.png",
      "REDIRECT_TYPE": 2,
      "REDIRECT_URL": null,
      "REDIRECT_PARAMS": "http:\/\/wximg.ycvod.cn\/VIPbiaozhi2.png",
      "CREATED_BY": null,
      "CREATED_TIME": null,
      "UPDATED_BY": "Administrator",
      "UPDATED_TIME": "2021-05-08 16:36:45",
      "SHOW_NAME": "没有特效&微信点歌授权登录后，大屏幕会出现VIP会员专属登场特效",
      "PAGE_URL": null,
      "SAMPLE_TYPE": null,
      "SAMPLE_URL": null,
      "FREE_TRIAL_TYPE": null,
      "COVER_IMG": null,
      "VERSION": "",
      "PAY_TYPE": "hy_lx",
      "NORMAL_INTRO": "没有特效",
      "VIP_INTRO": "微信点歌授权登录后，大屏幕会出现VIP会员专属登场特效"
    }, {
      "ID": 2310,
      "TYPE": "",
      "MENU_TYPE": 5,
      "MENU_NAME": "中车专属破解",
      "MENU_SORT": 900,
      "IS_ENABLE": "1",
      "MENU_COMMENTS": "更换头像、昵称",
      "MENU_ICON_URL": "https:\/\/zzyy.resource.i-ktv.com\/app_icon\/icon_gxzb_2.png",
      "REDIRECT_TYPE": 2,
      "REDIRECT_URL": null,
      "REDIRECT_PARAMS": "http:\/\/pwgrcsdx9.bkt.clouddn.com\/uploadvideo-vip-detail-new.png.png",
      "CREATED_BY": null,
      "CREATED_TIME": null,
      "UPDATED_BY": null,
      "UPDATED_TIME": null,
      "SHOW_NAME": "无法更改头像、昵称&随意更改头像、昵称",
      "PAGE_URL": null,
      "SAMPLE_TYPE": null,
      "SAMPLE_URL": null,
      "FREE_TRIAL_TYPE": 0,
      "COVER_IMG": "",
      "VERSION": "",
      "PAY_TYPE": "hy_lx",
      "NORMAL_INTRO": "无法更改头像、昵称",
      "VIP_INTRO": "随意更改头像、昵称"
    }],
    "vip_price": [{
      "ID": 1,
      "VIP_NAME": "1个月",
      "VIP_DURATION": "30",
      "VIP_ORIGINAL_PRICE": "30.00",
      "COMMON_SALES_PRICE": "16.80",
      "VIP_SALES_PRICE": "16.80",
      "PROMO_SALES_PRICE": "16.80",
      "IS_PROMOTE": "0",
      "PROMO_TARGET": 3,
      "CREATED_BY": "chenyong",
      "CREATED_TIME": "2019-08-19 22:13:33",
      "UPDATED_BY": "chenyong",
      "UPDATED_TIME": "2019-08-19 22:13:33",
      "IS_SHOW": 1,
      "IS_BOX_VIP": 0,
      "BUSINESS_TYPE": ""
    }, {
      "ID": 2,
      "VIP_NAME": "6个月",
      "VIP_DURATION": "180",
      "VIP_ORIGINAL_PRICE": "120.00",
      "COMMON_SALES_PRICE": "28.80",
      "VIP_SALES_PRICE": "28.80",
      "PROMO_SALES_PRICE": "28.80",
      "IS_PROMOTE": "0",
      "PROMO_TARGET": 3,
      "CREATED_BY": "chenyong",
      "CREATED_TIME": "2019-08-19 22:13:33",
      "UPDATED_BY": "chenyong",
      "UPDATED_TIME": "2019-08-19 22:13:33",
      "IS_SHOW": 1,
      "IS_BOX_VIP": 0,
      "BUSINESS_TYPE": ""
    }, {
      "ID": 3,
      "VIP_NAME": "12个月",
      "VIP_DURATION": "365",
      "VIP_ORIGINAL_PRICE": "200.00",
      "COMMON_SALES_PRICE": "39.80",
      "VIP_SALES_PRICE": "39.80",
      "PROMO_SALES_PRICE": "39.80",
      "IS_PROMOTE": "0",
      "PROMO_TARGET": 3,
      "CREATED_BY": "chenyong",
      "CREATED_TIME": "2019-08-19 22:13:33",
      "UPDATED_BY": "chenyong",
      "UPDATED_TIME": "2019-08-19 22:13:33",
      "IS_SHOW": 1,
      "IS_BOX_VIP": 0,
      "BUSINESS_TYPE": ""
    }];
body = JSON.stringify(vip);
}
$done({body});



